;;; UCHI Expediente técnico (resumen base)

(defun uchi:exp-file-status (name)
  (if (findfile (strcat (uchi:launcher-dir-safe) "/" name)) "OK" "FALTA")
)

(defun uchi:exp-write-disc-csv (/ path fp)
  (setq path (strcat (uchi:launcher-dir-safe) "/uchi_expediente_cuadros.csv"))
  (setq fp (open path "w"))
  (if fp
    (progn
      (write-line "disciplina,archivo,estado" fp)
      (write-line (strcat "TOPO,uchi_surface.xml," (uchi:exp-file-status "uchi_surface.xml")) fp)
      (write-line (strcat "TOPO,uchi_report.txt," (uchi:exp-file-status "uchi_report.txt")) fp)
      (write-line (strcat "URBANISMO,uchi_subdivision.csv," (uchi:exp-file-status "uchi_subdivision.csv")) fp)
      (write-line (strcat "URBANISMO,uchi_subdivision_summary.csv," (uchi:exp-file-status "uchi_subdivision_summary.csv")) fp)
      (write-line (strcat "REDES,uchi_redes.csv," (uchi:exp-file-status "uchi_redes.csv")) fp)
      (write-line (strcat "REDES,uchi_interferencias.csv," (uchi:exp-file-status "uchi_interferencias.csv")) fp)
      (write-line (strcat "HIDRAULICA,uchi_hidraulica.csv," (uchi:exp-file-status "uchi_hidraulica.csv")) fp)
      (write-line (strcat "VIAL,uchi_pavimentos.csv," (uchi:exp-file-status "uchi_pavimentos.csv")) fp)
      (close fp)
    )
  )
)

(defun C:UCHI_EXPEDIENTE (/ path fp)
  (uchi:topo-init)
  (setq path (strcat (uchi:launcher-dir-safe) "/uchi_expediente.txt"))
  (setq fp (open path "w"))
  (if fp
    (progn
      (write-line "UCHI - Expediente técnico (resumen automático)" fp)
      (write-line "============================================" fp)
      (write-line (strcat "Proyecto: " (uchi:project-get "name")) fp)
      (write-line (strcat "Puntos: " (vl-princ-to-string (uchi:project-get "points_count"))) fp)
      (write-line (strcat "TIN triángulos: " (vl-princ-to-string (uchi:project-get "tin_triangles"))) fp)
      (write-line (strcat "Subdivisión lotes: " (vl-princ-to-string (uchi:project-get "subdivision_lots"))) fp)
      (write-line (strcat "Volumen corte: " (vl-princ-to-string (uchi:project-get "cut"))) fp)
      (write-line (strcat "Volumen relleno: " (vl-princ-to-string (uchi:project-get "fill"))) fp)
      (write-line (strcat "Interferencias: " (vl-princ-to-string (uchi:project-get "interf_count"))) fp)
      (write-line "Archivos de expediente:" fp)
      (write-line (strcat "- uchi_surface.xml: " (uchi:exp-file-status "uchi_surface.xml")) fp)
      (write-line (strcat "- uchi_report.txt: " (uchi:exp-file-status "uchi_report.txt")) fp)
      (write-line (strcat "- uchi_subdivision.csv: " (uchi:exp-file-status "uchi_subdivision.csv")) fp)
      (write-line (strcat "- uchi_subdivision_summary.csv: " (uchi:exp-file-status "uchi_subdivision_summary.csv")) fp)
      (write-line (strcat "- uchi_redes.csv: " (uchi:exp-file-status "uchi_redes.csv")) fp)
      (write-line (strcat "- uchi_hidraulica.csv: " (uchi:exp-file-status "uchi_hidraulica.csv")) fp)
      (write-line (strcat "- uchi_pavimentos.csv: " (uchi:exp-file-status "uchi_pavimentos.csv")) fp)
      (write-line (strcat "- uchi_interferencias.csv: " (uchi:exp-file-status "uchi_interferencias.csv")) fp)
      (write-line "Cuadros por disciplina: uchi_expediente_cuadros.csv" fp)
      (close fp)
      (uchi:exp-write-disc-csv)
      (uchi:log "Expediente técnico generado: uchi_expediente.txt")
    )
    (uchi:log "ERROR al generar expediente.")
  )
  (princ)
)

(princ)
