;;; UCHI QC routines

(defun uchi:qc-dup-rate (/ n d)
  (setq n (uchi:to-real (uchi:project-get "points_count")))
  (setq d (uchi:to-real (uchi:project-get "points_dup")))
  (if (> n 0) (/ d n) 0.0)
)

(defun uchi:qc-invalid-rate (/ n i)
  (setq n (+ (uchi:to-real (uchi:project-get "points_count")) (uchi:to-real (uchi:project-get "points_invalid"))))
  (setq i (uchi:to-real (uchi:project-get "points_invalid")))
  (if (> n 0) (/ i n) 0.0)
)

(defun uchi:qc-status (/ dup inv tri area ok)
  (setq dup (uchi:qc-dup-rate))
  (setq inv (uchi:qc-invalid-rate))
  (setq tri (atoi (vl-princ-to-string (uchi:project-get "mesh_triangles"))))
  (setq area (uchi:to-real (uchi:project-get "mesh_area")))
  (setq ok (and (< dup 0.15) (< inv 0.10) (> tri 0) (> area 0.0)))
  (list
    (cons "ok" ok)
    (cons "dup_rate" dup)
    (cons "inv_rate" inv)
    (cons "triangles" tri)
    (cons "area" area)
  )
)

(defun C:UCHI_QC (/ qc)
  (uchi:topo-init)
  (setq qc (uchi:qc-status))
  (uchi:project-set "qc_ok" (if (cdr (assoc "ok" qc)) 1 0))
  (uchi:project-set "qc_dup_rate" (cdr (assoc "dup_rate" qc)))
  (uchi:project-set "qc_inv_rate" (cdr (assoc "inv_rate" qc)))
  (uchi:project-save)
  (uchi:log
    (strcat
      "QC => estado=" (if (cdr (assoc "ok" qc)) "PASS" "FAIL")
      ", dup_rate=" (rtos (cdr (assoc "dup_rate" qc)) 2 3)
      ", inv_rate=" (rtos (cdr (assoc "inv_rate" qc)) 2 3)
      ", tri=" (itoa (cdr (assoc "triangles" qc)))
      ", area=" (rtos (cdr (assoc "area" qc)) 2 2)
    )
  )
  (princ)
)

(defun C:UCHI_RELEASE_GO (/ qc)
  (C:UCHI_PROCESAR)
  (setq qc (uchi:qc-status))
  (if (cdr (assoc "ok" qc))
    (uchi:log "RELEASE GO: criterios mínimos QC cumplidos.")
    (uchi:log "RELEASE NO-GO: corregir datos/modelo antes de liberar.")
  )
  (princ)
)

(princ)
