# DG-2018 Perú - categoría vía nacional (referencial)
UCHI_CFG_TEMPLATE_NAME=DG-2018_PE_NACIONAL
UCHI_CFG_DESIGN_SPEED_KMH=80
UCHI_CFG_ROAD_CLASS=VIA_NACIONAL
UCHI_CFG_ROAD_LANE_WIDTH=3.60
UCHI_CFG_ROAD_LANES=2
UCHI_CFG_ROAD_SHOULDER=2.40
UCHI_CFG_ROAD_CROSSFALL=2.5
UCHI_CFG_ROAD_RMIN_M=230
UCHI_CFG_ROAD_GRADE_MAX_PCT=6.0
UCHI_CFG_ROAD_MAX_SUPERELEV=8.0
