# UCHI plantilla DG-2018 Carreteras Perú (editable externamente)
UCHI_CFG_ROAD_LANE_WIDTH=3.60
UCHI_CFG_ROAD_LANES=2
UCHI_CFG_ROAD_SHOULDER=1.80
UCHI_CFG_ROAD_CROSSFALL=2.5
UCHI_CFG_PROFILE_HSCALE=1.0
UCHI_CFG_PROFILE_VSCALE=10.0
UCHI_CFG_SUBDIV_ROAD_ANGLE=15
