# UCHI plantilla DG-2018 Carreteras Perú (editable externamente)
# ------------------------------------------------------------------------------
# Diseño geométrico vial (base referencial; ajustar por categoría IMDA/terreno)
# ------------------------------------------------------------------------------
UCHI_CFG_TEMPLATE_NAME=DG-2018_PE
UCHI_CFG_TEMPLATE_VERSION=1.0
UCHI_CFG_ROAD_CLASS=VIA_VECINAL
UCHI_CFG_DESIGN_SPEED_KMH=40
UCHI_CFG_TERRAIN_TYPE=ONDULADO

# Sección transversal típica
UCHI_CFG_ROAD_LANE_WIDTH=3.60
UCHI_CFG_ROAD_LANES=2
UCHI_CFG_ROAD_SHOULDER=1.80
UCHI_CFG_ROAD_BERM_WIDTH=0.50
UCHI_CFG_ROAD_CARRIAGEWAY_CROWN=2.0
UCHI_CFG_ROAD_CROSSFALL=2.5
UCHI_CFG_ROAD_MAX_SUPERELEV=8.0
UCHI_CFG_ROAD_PLATFORM_WIDTH=10.80

# Curvatura horizontal
UCHI_CFG_ROAD_RMIN_M=80
UCHI_CFG_ROAD_LC_MIN_M=40
UCHI_CFG_ROAD_TRANSITION_MIN_M=30
UCHI_CFG_ROAD_WIDENING_ENABLE=1
UCHI_CFG_ROAD_WIDENING_MAX_M=0.80

# Rasante y control vertical
UCHI_CFG_ROAD_GRADE_MIN_PCT=0.50
UCHI_CFG_ROAD_GRADE_MAX_PCT=8.00
UCHI_CFG_ROAD_KVCREST_MIN=12
UCHI_CFG_ROAD_KVSAG_MIN=10
UCHI_CFG_PROFILE_HSCALE=1.0
UCHI_CFG_PROFILE_VSCALE=10.0
UCHI_CFG_PROFILE_PK_STEP=20
UCHI_CFG_PROFILE_GRID_Z=1.0
UCHI_CFG_PROFILE_RASANTE_OFFSET=0.00

# Taludes y plataforma
UCHI_CFG_ROAD_CUT_SLOPE_HV=1.5
UCHI_CFG_ROAD_FILL_SLOPE_HV=2.0
UCHI_CFG_ROAD_DITCH_ENABLE=1
UCHI_CFG_ROAD_DITCH_DEPTH=0.50
UCHI_CFG_ROAD_DITCH_WIDTH=1.00

# Drenaje longitudinal/transversal
UCHI_CFG_DRAIN_INT=20
UCHI_CFG_DRAIN_OFFSET=4.0
UCHI_CFG_DRAIN_WIDTH=2.0
UCHI_CFG_DRAIN_DEPTH=0.5
UCHI_CFG_DRAIN_MIN_SLOPE_PCT=0.5

# Replanteo y estacado
UCHI_CFG_STAKEOUT_INT=20
UCHI_CFG_STAKEOUT_OFFSET=5.0

# Redes/servicios (si aplica en corredor vial urbano)
UCHI_CFG_WATER_DIAM_MM=110
UCHI_CFG_WATER_SLOPE_PCT=0.5
UCHI_CFG_SEWER_DIAM_MM=200
UCHI_CFG_SEWER_SLOPE_PCT=1.0
UCHI_CFG_BZ_SPACING=60

# Subdivisión/parcelario asociado al corredor
UCHI_CFG_SUBDIV_COLS=6
UCHI_CFG_SUBDIV_ROWS=6
UCHI_CFG_SUBDIV_NDIV=0
UCHI_CFG_SUBDIV_ROAD_EVERY=3
UCHI_CFG_SUBDIV_ROAD_ANGLE=15
UCHI_CFG_SUBDIV_MIN_AREA=80
UCHI_CFG_SUBDIV_MIN_FRONT=6
UCHI_CFG_SUBDIV_APORTE_PCT=8

# Curvas de nivel y presentación
UCHI_CFG_CURVE_MAJOR=5
UCHI_CFG_CURVE_MINOR=1
UCHI_CFG_SECTION_INTERVAL=20
UCHI_CFG_SECTION_WIDTH=20
UCHI_CFG_SECTION_HEIGHT=8
UCHI_CFG_SECTION_COLS=4
