# DG-2018 Perú - categoría vía vecinal (referencial)
UCHI_CFG_TEMPLATE_NAME=DG-2018_PE_VECINAL
UCHI_CFG_DESIGN_SPEED_KMH=30
UCHI_CFG_ROAD_CLASS=VIA_VECINAL
UCHI_CFG_ROAD_LANE_WIDTH=3.30
UCHI_CFG_ROAD_LANES=2
UCHI_CFG_ROAD_SHOULDER=1.20
UCHI_CFG_ROAD_CROSSFALL=2.5
UCHI_CFG_ROAD_RMIN_M=50
UCHI_CFG_ROAD_GRADE_MAX_PCT=10.0
UCHI_CFG_ROAD_MAX_SUPERELEV=8.0
